### ISSUE TITLE
Multiple languages listed on a feed post are not handled properly

### ISSUE THREAD

**Issue by imax9000** [skyfeed-dev/query-engine#1]
Looking at the code, is seems that it's currently only taking the first entry from the `langs` array into account, and defaults to English if the language is not specified.

This interferes with a couple of interesting use cases:
* (obviously) matching additional languages specified on a post
* matching posts that have *only* a selected language specified

**Comment by redsolver** [comment]
hey thanks for the issue, the idea behind this approach was to keep the SkyFeed Builder simple for all common use cases, considering that 99.9%+ of all posts should be tagged with exactly one language if the feature were to be used correctly

**Comment by imax9000** [comment]
1. That expectation doesn't match the data model
2. Empirically, the amount of posts with more than one language listed is about 20%

**Comment by imax9000** [comment]
![image](https://github.com/skyfeed-dev/query-engine/assets/654649/66d91934-be41-4797-a0f9-bd5aa8c3efa5)

**Comment by redsolver** [comment]
Could you please check the current percentage of posts tagged with more than one language? I think it should now be significantly lower.

**Comment by imax9000** [comment]
Yup, now it's mostly floating between 0.5%-1%. I think it's still worth to account for multiple languages in a single post, but feel free to close this if you think it's not worth the effort.
